#numpy tutorial

In [1]:
import numpy as np
import sys
import time


#Numpy Array & List

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
print(a[0])

1


In [4]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


#Comparison of Size between Numpy array and python list

In [5]:
array=np.arange(1000)   
print(array.size*array.itemsize)


8000


In [6]:
l=range(1000)
print(sys.getsizeof(2)*len(l)) 

28000


#Comparison of time between Numpy array and python list

In [7]:
size=100000000
l1=range(size)
l2=range(size)

a1=np.arange(size)
a2=np.arange(size)

#python list 
start= time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("Python list took time:",(time.time()-start)*1000)

#numpy array
start=time.time()
result=a1+a2
print("Numpy array took time :",(time.time()-start)*1000)


Python list took time: 18787.752389907837
Numpy array took time : 416.5210723876953


#zip

In [8]:
l1=['apple','orange','banana']
l2=['fayez','udoy','ayon']
zi1=zip(l1,l2)
zi2=zip(l2,l2)
zi3=zip(l1,l1)
print("Zi1 denotes: ",list(zi1))
print("Zi2 denotes", list(zi2))
print("Zi3 denotes", list(zi3))
print("This zip denotes:", list(zip(range(5),range(6),range(50))))

Zi1 denotes:  [('apple', 'fayez'), ('orange', 'udoy'), ('banana', 'ayon')]
Zi2 denotes [('fayez', 'fayez'), ('udoy', 'udoy'), ('ayon', 'ayon')]
Zi3 denotes [('apple', 'apple'), ('orange', 'orange'), ('banana', 'banana')]
This zip denotes: [(0, 0, 0), (1, 1, 1), (2, 2, 2), (3, 3, 3), (4, 4, 4)]


#Basic array operation

In [9]:
#ndim
a=np.array([[1,2],[3,4],[5,6]])
print(a.ndim)

2


In [10]:
a=np.array([5,6,7])
print(a.ndim)

1


In [11]:
#itemsize
a=np.array([[1,2],[3,4],[5,6]])
print(a.itemsize)

8


In [12]:
a=np.array([5,6,7])
print(a.itemsize)

8


In [13]:
#float,complex,dtype

a=np.array([[1,2],[3,4],[5,6]])
print(a.itemsize)
print(a)
print(a.dtype)

8
[[1 2]
 [3 4]
 [5 6]]
int64


In [14]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
print(a.itemsize)
print(a)

8
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [15]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.complex128)
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [16]:
#size, shape

a=np.array([[1,2],[3,4],[5,6]])
print(a.size)
print(a.shape)

6
(3, 2)


In [80]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
b=np.ones((3,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
l=range(5)
print(l)
print(l[4])
print(l[2])

range(0, 5)
4
2


In [20]:
a=np.arange(1, 5,2)
print(a)
a=np.arange(5,100,5)
print(a)

[1 3]
[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [21]:
a=np.linspace(1,5,10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [22]:
a=np.linspace(1,10,20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [23]:
a=np.array([[1,2],[4,5],[7,8]])
print("The shape of NumPy array is: ", a.shape)

print("The NumPy array before reshape: \n\n", a)

The shape of NumPy array is:  (3, 2)
The NumPy array before reshape: 

 [[1 2]
 [4 5]
 [7 8]]


In [24]:
print(a.reshape(2,3))

[[1 2 4]
 [5 7 8]]


In [25]:
print(a.reshape(6,1))

[[1]
 [2]
 [4]
 [5]
 [7]
 [8]]


In [26]:
print(a)
print("\n")
print(a.ravel())

[[1 2]
 [4 5]
 [7 8]]


[1 2 4 5 7 8]


In [27]:
print(a)
print("\n")
print("The max value of the array is: ",a.max())
print("\n")
print("The min value of the array is: ",a.min())

[[1 2]
 [4 5]
 [7 8]]


The max value of the array is:  8


The min value of the array is:  1


In [28]:
print(a)
print("\n")
print(a.sum())

[[1 2]
 [4 5]
 [7 8]]


27


In [29]:
print(a.sum(axis=0))

[12 15]


In [30]:
print(a.sum(axis=1))

[ 3  9 15]


In [31]:
print(np.sqrt(a))

[[1.         1.41421356]
 [2.         2.23606798]
 [2.64575131 2.82842712]]


In [32]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a+b)

[[ 6  8]
 [10 12]]


In [33]:

print(a-b)

[[-4 -4]
 [-4 -4]]


In [34]:

print(a/b)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [35]:

print(a*b)

[[ 5 12]
 [21 32]]


In [36]:

print(a.dot(b))

[[19 22]
 [43 50]]


#indexing of numpy array

In [93]:
m=[1,2,3,4]
print(l[0:3])

[1, 2, 3]


In [38]:
print(l[:])

[1, 2, 3, 4]


In [39]:
print(l[:-1])

[1, 2, 3]


In [40]:
#indexing of numpy array


a=np.array([6,7,8])
print(a[:])

[6 7 8]


In [41]:
print(a[-1])

8


In [42]:
#multidimentional array
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
print(a)

[[6 7 8]
 [1 2 3]
 [9 3 2]]


In [43]:
print(a[2,2])

2


In [44]:
print(a[0:2,2])

[8 3]


In [45]:
print(a[0,1:3])

[7 8]


In [46]:
print(a[-1])

[9 3 2]


In [47]:
print(a[-1,0:2])

[9 3]


In [48]:
print(a[:,0:3])

[[6 7 8]
 [1 2 3]
 [9 3 2]]


#Iterating of numpy array


In [81]:
a=np.array([[6,10,8],[0,0,12],[2,30,5]])
print(a)

[[ 6 10  8]
 [ 0  0 12]
 [ 2 30  5]]


In [82]:
for row in a:
  print(row)

[ 6 10  8]
[ 0  0 12]
[ 2 30  5]


In [51]:
for cell in a:
  print(cell)

[6 7 8]
[1 2 3]
[9 3 2]


In [52]:
for cell in a.flat:
  print(cell)

6
7
8
1
2
3
9
3
2


In [53]:
for row in a.flat:
  print(row)

6
7
8
1
2
3
9
3
2


#stacks on numpy array


In [87]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [88]:
a=np.arange(6).reshape(3,2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [89]:
b=np.arange(6,12).reshape(3,2)
print(b)

[[ 6  7]
 [ 8  9]
 [10 11]]


In [92]:
print(np.vstack((a,b)))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [58]:
print(np.vstack((b,a)))

[[ 6  7]
 [ 8  9]
 [10 11]
 [ 0  1]
 [ 2  3]
 [ 4  5]]


In [59]:
print(np.hstack((a,b)))

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [60]:
print(np.hstack((b,a)))

[[ 6  7  0  1]
 [ 8  9  2  3]
 [10 11  4  5]]


In [61]:
a=np.arange(30).reshape(2,15)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [62]:
result=np.hsplit(a,3)
print(result[0])
print(result[1])
print(result[2])

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [63]:
result=np.vsplit(a,2)
print(result[0])
print(result[1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [64]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
b=a>4
print(b)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [66]:
print(a[b])

[ 5  6  7  8  9 10 11]


In [67]:
a[b]=-1
print(a)

[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


#Iterate numpy array using nditer

In [68]:
a=np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [69]:
for cell in a:
  print(cell)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [70]:
for row in a:
  print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [71]:
#where two for loop required
for row in a:
  for cell in row:
    print(cell)


0
1
2
3
4
5
6
7
8
9
10
11


In [72]:
#only one for loop required
for cell in a.flatten():
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [73]:
#a.flat and a.flatten() do the same function
for cell in a.flat:
  print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [74]:
#instead of using flat or flatter, we can use nditer for numpy array


for x in np.nditer(a,order='C'):
    print(x)




0
1
2
3
4
5
6
7
8
9
10
11


In [75]:
# fortan style
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [76]:
# function of flags
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [77]:
#function of op_flags
for x in np.nditer(a,op_flags=['readwrite']):
  x[...]=x*x
print(a)  


[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [78]:
#iterate two arrays simultaneously 

a=np.arange(12).reshape(3,4)
print(a)
print("\n")
b=np.arange(3,15,4).reshape(3,1)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 3]
 [ 7]
 [11]]


In [79]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


In [ ]:
print("Mohammad Fayez Ullah ")